### ISSUE TITLE
Can we mention this extension in VS Code python extension blog?

### ISSUE THREAD

**Issue by karthiknadig** [omnilib/vscode-ufmt#17]
Thank you for using the extension template for python tools. We were wondering if it was OK for us to mention ufmt extension in our blogs.
/cc @luabud

**Comment by amyreese** [comment]
Generally speaking, yes, I would love for you to mention this in the blog. However, I'm still chasing down some issues that cause the server to crash and require reloading, especially in cases where the environment does not already have a compatible copy of ufmt. What sort of timeline is there before the next announcement? I will try to get that tracked down and have a solution soon, but not sure if I will have the time.

**Comment by karthiknadig** [comment]
@amyreese For the crash... I recommend you set the default for your extension to be `ufmt.importStrategy` = `useBundled`. This will ensure that extension always picks up the bundled libraries.

**Comment by karthiknadig** [comment]
For the announcement, we have a monthly release blog. We were planning for the next one in October. But, we can wait until you are Ok with it.

**Comment by amyreese** [comment]
I think I'm happy with the latest release now, so everything is "Go" from my end. :)

**Comment by amyreese** [comment]
@karthiknadig since it's October now, is there anything you need from me at this point?

**Comment by cwebster-99** [comment]
@amyreese We just published the October release blog where we mentioned the ufmt extension. Thank you for using the template and your contribution! 
https://devblogs.microsoft.com/python/python-in-visual-studio-code-october-2022-release/

**Comment by amyreese** [comment]
Thank you :)
