### ISSUE TITLE
Option for configuring line length?

### ISSUE THREAD

**Issue by yhcharles** [omnilib/vscode-ufmt#32]
For black, we can set the line length in "Python > Formatting: Black Args". Is it possible to have something similar for ufmt?
Thanks!

**Comment by amyreese** [comment]
This is a bit tricky given the way the extension is implemented. Is there a reason that you don't define your preferred line length in a `pyproject.toml`, where it can be read and obeyed by ufmt/black, regardless of whether it's running from VS Code or CLI?
