### ISSUE TITLE
formatter crushes after formatting more than twice

### ISSUE THREAD

**Issue by bilzard** [omnilib/vscode-ufmt#84]
after "Format Document With..." -> "ufmt" twice, formatter crushes with error popup:

> uncaught exception: Traceback (most recent call last): File "/root/.vscode-server-insiders/extensions/omnilib.ufmt-2023.4.3-linux-x64/bundled/tool/server.py", line 341, in _run_tool_on_document ufmt_result = ufmt.ufmt_bytes( File "/usr/local/lib/python3.10/dist-packages/ufmt/core.py", line 84, in ufmt_bytes raise result.error File "/usr/local/lib/python3.10/dist-packages/usort/api.py", line 31, in usort module = try_parse(data=data, path=path) File "/usr/local/lib/python3.10/dist-packages/usort/util.py", line 65, in try_parse mod = cst.parse_module( File "/usr/local/lib/python3.10/dist-packages/libcst/_parser/entrypoints.py", line 109, in parse_module result = _parse( File "/usr/local/lib/python3.10/dist-packages/libcst/_parser/entrypoints.py", line 42, in _parse from libcst.native import parse_expression, parse_module, parse_statement ImportError: PyO3 modules may only be initialized once per interpreter process

### System Configuration

```
µfmt: v2023.4.3
python: 3.10.12
VSCode: 1.82.0-insider
```

**Comment by Synse** [comment]
Try `"ufmt.importStrategy": "useBundled"` as mentioned here: https://github.com/omnilib/vscode-ufmt/issues/83#issuecomment-1650403713

**Comment by amyreese** [comment]
Just published a new release that defaults to "useBundled" and also disables the attempt to reload extensions, which together should resolve this problem.
